Override identification of gzipped WARCs
sul-dlss/technical-metadata-service pull request #361
Opened 2022-07-07 22:41 UTC by mjgiarlo

## Why was this change made? 🤔

Fixes #343
    
This commit adds logic to the `FileIdentifierService` allowing it to detect when it has been asked to identify a gzipped WARC file and, when it has, to return the file format information of a non-gzipped WARC file. Requested by product owner to provide more useful information about web archives.

Also includes:

* Point app and worker docker-compose services at docker Redis URL: without this commit, `docker-compose up workers` would not successfully bring up the workers.

## How was this change tested? 🤨

CI, and run locally against the new fixture WARC.

2022-07-07 22:53 UTC, ndushay approved these changes
LGTM

2022-07-08 02:02 UTC, jcoyne commented on app/services/file_identifier_service.rb
> +    return [pronom_id, mimetype] unless pronom_id == 'x-fmt/266' &&
Doesn't the first clause (`x-fmt/266`) imply the second (`application/gzip`)?  Do we need both clauses?

2022-07-08 02:03 UTC, jcoyne requested changes

2022-07-08 02:03 UTC, jcoyne commented on docker-compose.yml
> +      SETTINGS__REDIS_URL: redis://redis:6379/
Why is this required in this pr?

2022-07-08 02:04 UTC, jcoyne commented on docker-compose.yml
> +      SETTINGS__REDIS_URL: redis://redis:6379/
Ah, I see the separate commit message.

2022-07-08 02:04 UTC, jcoyne approved these changes

2022-07-08 17:17 UTC, merged